### PR TITLE
Fix/docs generation on Vercel

### LINKED ISSUE #246: Documentation: Vercel deploy previews failing
**Describe the bug**
Recently documentation deployments started to fail on Vercel. Need to debug and check with Vercel team what's causing this.

Based on logs it shows that the deploy didn't finish. So it hangs after generating all pages without ending the Node process.

**To Reproduce**
1. Open pull request
2. Deploy check always fails.

**Expected behavior**
Deploy previews should be successful if no changes are made to the deployment config or generation code.

**Additional context**
This might be mostly on Vercels end or perhaps an internal memory issue. Need to check why it hangs after generation.

### PR DESCRIPTION
**Pull request by codebender828**
Closes #246
This was caused by some hanging functions during generation on some old routes.

**Other changes**
- [x] Upgrades to Nuxt 2.13
- [x] Removed old documentation code.

## How Has This Been Tested?
Deploy preview should successfully be deployed [here](https://chakra-ui-vue-git-fix-docs-generation.chakra-ui.vercel.app)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/chakra-ui-docs/static/sw.js [hunk 1]
```diff
@@ -1 +1,32 @@
-// THIS FILE SHOULD NOT BE VERSION CONTROLLED
+importScripts('https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-sw.js')
```
Comment (codebender828) [inline packages/chakra-ui-docs/static/sw.js:1]: Will remove this file
